Add X-Metrics-Calculator response header
athenianco/athenian-api pull request #1367
Opened 2021-04-26 16:42 UTC by se7entyse7en

Closes [DEV-2194](https://athenianco.atlassian.net/browse/DEV-2194).

2021-04-26 17:11 UTC, vmarkovtsev requested changes
Only one thing.

2021-04-26 17:11 UTC, vmarkovtsev commented on server/athenian/api/controllers/status_controller.py
> +    request.app["metrics-calculator"].set(defaultdict(str))
Can you please use underscore vs. dash

```suggestion
    request.app["metrics_calculator"].set(defaultdict(str))
```

2021-04-27 08:17 UTC, se7entyse7en commented on server/athenian/api/controllers/status_controller.py
> +    request.app["metrics-calculator"].set(defaultdict(str))
right, sorry, I overlooked it

2021-04-27 08:46 UTC, vmarkovtsev approved these changes

2021-04-27 08:50 UTC, merged