[DEV-4086] graphql members query
athenianco/athenian-api pull request #2367
Opened 2022-05-18 13:44 UTC by gaetano-guerriero

2022-05-18 13:59 UTC, gaetano-guerriero commented on server/athenian/api/controllers/account.py
> -@cached(
moved some stuff so that graphql code doesn't need to access `controllers` package

2022-05-18 14:23 UTC, vmarkovtsev requested changes

2022-05-18 14:23 UTC, vmarkovtsev commented on server/athenian/api/controllers/features/everything.py
> +    MergedPRFactsLoader, OpenPRFactsLoader
I see that you've reformatted the imports. Can you please extract this formatting in a separate PR :pray:

2022-05-18 18:00 UTC, vmarkovtsev requested changes

2022-05-19 06:45 UTC, gaetano-guerriero commented on server/athenian/api/controllers/team_controller.py
> +    members = await get_contributors(
reverted to `get_all_team_members`

2022-05-19 06:50 UTC, gaetano-guerriero commented on server/athenian/api/controllers/team_controller.py
> +    )
Yes I'm aware cast is a no-op at runtime, I was fixing the type for mypy. Anyway as you said the argument for `get_all_team_members` can be an iterable

2022-05-19 06:52 UTC, gaetano-guerriero commented on server/athenian/api/controllers/team_controller.py
> +from sqlalchemy.engine.row import Row
At least locally I get`sa.engine.row.Row` or `asyncpg.Record`.
Anyway, isn't `Mapping[str, Any]` more correct ?
```
(Pdb) team_rows[0]["foo"] = "bar"
*** TypeError: 'asyncpg.Record' object does not support item assignment
(Pdb) del team_rows[0]["id"]
*** TypeError: 'asyncpg.Record' object does not support item deletion
```

2022-05-19 06:57 UTC, gaetano-guerriero commented on server/athenian/api/controllers/team_controller.py
> +                           ) -> Dict[int, Contributor]:
This is the OpenAPI generated model should be renamed there as well ?
The same type is also used for `/get/contributors/{id}/` or `/filter/contributors`/

2022-05-19 07:09 UTC, gaetano-guerriero commented on server/athenian/api/align/queries/members.py
> +    if actual_team_id is not None and not (await team_exists(accountId, teamId, sdb)):
fixed

2022-05-19 07:14 UTC, gaetano-guerriero commented on server/athenian/api/controllers/team_controller.py
> +    team_rows = await _recursive_teams_fetch(account_id, sdb_conn, (Team.members,), root_team_id)
Ok I wasn't expecting that.
Anyway sometimes this is not  true
```
state=> select COUNT(*) from teams t0 JOIN teams t1 ON t0.parent_id = t1.id WHERE NOT (t1.members::jsonb @> t0.members::jsonb);
 count
-------
    15
```

2022-05-19 07:18 UTC, gaetano-guerriero commented on server/athenian/api/controllers/team_controller.py
> +    team_rows = await _recursive_teams_fetch(account_id, sdb_conn, (Team.members,), root_team_id)
On a related topic, then we are expecting to add all members to the artificial Root team ?

2022-05-19 07:22 UTC, gaetano-guerriero commented on server/athenian/api/controllers/team_controller.py
> +    account_id: int, sdb_conn: DatabaseLike, root_team_id: int = None,
Ok, this was implicit not long ago

https://peps.python.org/pep-0484/

> A past version of this PEP allowed type checkers to assume an optional type when the default value is None, as in this code:

2022-05-19 07:27 UTC, vmarkovtsev commented on server/athenian/api/controllers/team_controller.py
> +from sqlalchemy.engine.row import Row
Yep it should be a Mapping ✔️

2022-05-19 07:29 UTC, vmarkovtsev commented on server/athenian/api/controllers/team_controller.py
> +                           ) -> Dict[int, Contributor]:
Ah so this is an existing model, then OK 👍
Those endpoints return any people who contributed, so should be fine. Thanks for double-checking.

2022-05-19 07:33 UTC, vmarkovtsev commented on server/athenian/api/controllers/team_controller.py
> +    team_rows = await _recursive_teams_fetch(account_id, sdb_conn, (Team.members,), root_team_id)
I think this is happening:
- The teams are always nested.
- GitHub reports only the extra team members for each team - that is, those who are outside of the child teams.

Let's double check by looking at our clients teams in production.

2022-05-19 12:29 UTC, vmarkovtsev requested changes
I think we are very close to merging!

2022-05-19 12:29 UTC, vmarkovtsev commented on server/athenian/api/controllers/team_controller.py
> +from athenian.api.align.exceptions import TeamNotFoundError
Let's move this exception to the team controller for now. We should properly refactor later ofc, but we will at least avoid importing align inside the controllers and the potential circular imports.

2022-05-19 12:29 UTC, vmarkovtsev commented on server/athenian/api/controllers/team_controller.py
> +    return bool(await sdb_conn.fetch_val(stmt))
Do we still need this function?

2022-05-19 12:29 UTC, vmarkovtsev commented on server/athenian/api/controllers/team_controller.py
> +    # a recursive CTE is used to link children teams and track depth
As we discussed, let's change to the simple team members fetch or loading the org members if id = 0

2022-05-19 14:33 UTC, vmarkovtsev approved these changes

2022-05-19 14:33 UTC, merged