[DEV-5735] metrics calc jira multiple groups
athenianco/athenian-api pull request #3351
Opened 2023-02-09 13:53 UTC by gaetano-guerriero

2023-02-09 13:56 UTC, gaetano-guerriero commented on server/athenian/api/internal/miners/jira/issue.py
> +                ", ".join(map(str, issues.index.values[missing_updated])),
'key' column is not  not always present

2023-02-14 09:17 UTC, vmarkovtsev commented
Overall, LGTM :+1:

2023-02-14 09:52 UTC, gaetano-guerriero reviewed
> *[Reviewable](https://reviewable.io/reviews/athenianco/athenian-api/3351)* status: 0 of 11 files reviewed, 2 unresolved discussions (waiting on @vmarkovtsev)

___
*[`server/athenian/api/internal/features/entries.py` line 1246 at r1](https://reviewable.io/reviews/athenianco/athenian-api/3351#-NOEBsLJ3z5Q9ggYzg6f:-NOEJnATElJvtXkC_8Oy:by8pasg) ([raw file](https://github.com/athenianco/athenian-api/blob/145559b9caa3de3918fd2bc197efca95b290eb0c/server/athenian/api/internal/features/entries.py#L1246)):*
<details><summary><i>Previously, vmarkovtsev (Vadim Markovtsev) wrote…</i></summary><blockquote>

`jira_ids` are globally unique and may not change. It is always the same for all the groups and should be left here
</blockquote></details>

I could add it back but where will it be used ?
The problem is the dual nature of `JIRAFilter` which carries both the user filtering and the account status, so someway replace `JIRAConfig`
`fetch_jira_issue` already does not receive `JIRAConfig`
To convert entities for the grouping `JIRAFilter`s are used, only `account` is needed.
`calc_pull_request_metrics_line_github` already accepts only `JIRAFilter` and no `JIRAConfig` given that the needed information are carried by `JIRAFilter`


<!-- Sent from Reviewable.io -->

2023-02-14 12:19 UTC, vmarkovtsev requested changes
> *[Reviewable](https://reviewable.io/reviews/athenianco/athenian-api/3351)* status: 0 of 11 files reviewed, 3 unresolved discussions (waiting on @gaetano-guerriero)

___
*[`server/athenian/api/internal/features/entries.py` line 1251 at r2](https://reviewable.io/reviews/athenianco/athenian-api/3351#-NOEr15b3ZKfqDs_nqhY:-NOEr15b3ZKfqDs_nqhZ:bj1hgdg) ([raw file](https://github.com/athenianco/athenian-api/blob/a6f4adcdd4574b2f0fbf273f43dd63f9ff63c067/server/athenian/api/internal/features/entries.py#L1251)):*
> ```Python
>         # there should be at least one group, and every should include a valid jira account id
>         assert len(groups)
>         assert all(g.account for g in groups)
> ```

This is not enough: all the accounts must be exactly equal.
___
*[`server/athenian/api/internal/features/entries.py` line 1262 at r2](https://reviewable.io/reviews/athenianco/athenian-api/3351#-NOErLx77Zh4mwCG17B0:-NOErLx77Zh4mwCG17B1:b-d132no) ([raw file](https://github.com/athenianco/athenian-api/blob/a6f4adcdd4574b2f0fbf273f43dd63f9ff63c067/server/athenian/api/internal/features/entries.py#L1262)):*
> ```Python
>             assert len(groups) == 1
>             extra_columns.append(Issue.labels)
>             general_grouper = label_splitter
> ```

Let's name it `jira_filter_grouper`


<!-- Sent from Reviewable.io -->

2023-02-14 12:29 UTC, gaetano-guerriero reviewed
> *[Reviewable](https://reviewable.io/reviews/athenianco/athenian-api/3351)* status: 0 of 11 files reviewed, 3 unresolved discussions (waiting on @vmarkovtsev)

___
*[`server/athenian/api/internal/features/entries.py` line 1251 at r2](https://reviewable.io/reviews/athenianco/athenian-api/3351#-NOEr15b3ZKfqDs_nqhY:-NOEtYGQE9707Rcja3BR:b-896fix) ([raw file](https://github.com/athenianco/athenian-api/blob/a6f4adcdd4574b2f0fbf273f43dd63f9ff63c067/server/athenian/api/internal/features/entries.py#L1251)):*
<details><summary><i>Previously, vmarkovtsev (Vadim Markovtsev) wrote…</i></summary><blockquote>

This is not enough: all the accounts must be exactly equal.
</blockquote></details>

Done.
___
*[`server/athenian/api/internal/features/entries.py` line 1262 at r2](https://reviewable.io/reviews/athenianco/athenian-api/3351#-NOErLx77Zh4mwCG17B0:-NOEtXkG7OB2QVOu5Wbc:b-896fix) ([raw file](https://github.com/athenianco/athenian-api/blob/a6f4adcdd4574b2f0fbf273f43dd63f9ff63c067/server/athenian/api/internal/features/entries.py#L1262)):*
<details><summary><i>Previously, vmarkovtsev (Vadim Markovtsev) wrote…</i></summary><blockquote>

Let's name it `jira_filter_grouper`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-02-14 12:52 UTC, vmarkovtsev approved these changes
> *[Reviewable](https://reviewable.io/reviews/athenianco/athenian-api/3351)* status: 0 of 11 files reviewed, 1 unresolved discussion



<!-- Sent from Reviewable.io -->

2023-02-14 12:53 UTC, vmarkovtsev approved these changes
> *[Reviewable](https://reviewable.io/reviews/athenianco/athenian-api/3351)* status: 0 of 11 files reviewed, 1 unresolved discussion



<!-- Sent from Reviewable.io -->

2023-02-14 12:54 UTC, vmarkovtsev approved these changes
> *[Reviewable](https://reviewable.io/reviews/athenianco/athenian-api/3351)* status: 0 of 11 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-02-14 14:05 UTC, merged