[DEV-5735] metrics jira controller multiple groups
athenianco/athenian-api pull request #3371
Opened 2023-02-14 14:16 UTC by gaetano-guerriero

2023-02-14 15:22 UTC, gaetano-guerriero commented on server/athenian/api/controllers/jira_controller.py
> +        projects = jira_conf.project_ids_map(filt.projects)
no need to touch db again JIRAConfig has all the projects, we can compute the subset

2023-02-16 09:16 UTC, vmarkovtsev requested changes
> Reviewed 1 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/athenianco/athenian-api/3371)* status: 1 of 10 files reviewed, 2 unresolved discussions (waiting on @gaetano-guerriero)

___
*[`server/athenian/api/controllers/jira_controller.py` line 1438 at r1](https://reviewable.io/reviews/athenianco/athenian-api/3371#-NOOVX0a88PVdYiDp2FY:-NOOVX0a88PVdYiDp2FZ:bny9mvq) ([raw file](https://github.com/athenianco/athenian-api/blob/195703fb045631dc9029412a08d6db19fd852fa2/server/athenian/api/controllers/jira_controller.py#L1438)):*
> ```Python
>         res_groups = [None] * len(split_labels)
> 
>     granularities = metrics_req.granularities or ["all"]
> ```

`granularities` is a required field, there must be at least one element. We shouldn't do `or ["all"]`


<!-- Sent from Reviewable.io -->

2023-02-16 17:24 UTC, gaetano-guerriero reviewed
> *[Reviewable](https://reviewable.io/reviews/athenianco/athenian-api/3371)* status: 1 of 12 files reviewed, 3 unresolved discussions (waiting on @vmarkovtsev)

___
*[`server/athenian/api/controllers/jira_controller.py` line 1438 at r1](https://reviewable.io/reviews/athenianco/athenian-api/3371#-NOOVX0a88PVdYiDp2FY:-NOQEjvy6p0CUj72BNTF:bxkqlmj) ([raw file](https://github.com/athenianco/athenian-api/blob/195703fb045631dc9029412a08d6db19fd852fa2/server/athenian/api/controllers/jira_controller.py#L1438)):*
<details><summary><i>Previously, vmarkovtsev (Vadim Markovtsev) wrote…</i></summary><blockquote>

`granularities` is a required field, there must be at least one element. We shouldn't do `or ["all"]`
</blockquote></details>

Done.
I'll avoid this https://athenianco.atlassian.net/browse/DEV-5981 by fixing the spec then with `minItems: 1`
___
*[`server/athenian/api/internal/jira.py` line 107 at r1](https://reviewable.io/reviews/athenianco/athenian-api/3371#-NOOWgS--69-DOV2dC0G:-NOQEi0U7qS15Xodq71c:b-896fix) ([raw file](https://github.com/athenianco/athenian-api/blob/195703fb045631dc9029412a08d6db19fd852fa2/server/athenian/api/internal/jira.py#L107)):*
<details><summary><i>Previously, vmarkovtsev (Vadim Markovtsev) wrote…</i></summary><blockquote>

I checked: we convert this to a frozenset everywhere we use it. Let's return a frozenset directly then.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-02-16 22:22 UTC, vmarkovtsev approved these changes
> *[Reviewable](https://reviewable.io/reviews/athenianco/athenian-api/3371)* status: 1 of 12 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-02-16 22:23 UTC, merged